name: Publicar Documentación

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Instalar DocFX
        run: dotnet tool update -g docfx

      - name: Inicializar docfx si no existe
        run: |
          if [ ! -f docfx.json ]; then
            docfx init -q
          fi

      - name: Generar metadata y documentación
        run: |
          docfx metadata
          docfx build

      - name: Publicar en GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
